---
# Installation of apache/httpd

- name: gather OS info
  include_tasks: Redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: gather OS info
  include_tasks: Debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

